from enum import Enum

class AssessorNames(str, Enum):
    TIBERIAS = "טבריה"
    AFULA = "עפולה"
    ZFAT = "צפת"
    ZFAT2="צפת שלוחת רמת הגולן"
    NAZARETH = "נצרת"
    ACO="עכו"
    HAIFA = "חיפה"
    HADERA = "חדרה"
    RAANANA = "רעננה מרכז"
    KFAR_SABA = "כפר סבא"
    RAMLE = "רמלה"
    TEL_AVIV_1 = "תל אביב 1"
    TEL_AVIV_3 = "תל אביב 3"
    TEL_AVIV_5 = "תל אביב 5"
    TEL_AVIV_4 = "תל אביב 4"
    Gush_Dan = "גוש דן"
    JERUSALEM_1 = "ירושלים 1"
    JERUSALEM_2 = "ירושלים 2"
    JERUSALEM_3 = "ירושלים 3"
    OTONOMIA = "אוטונומיה"
    EILAT_WEMISUI_MEKARKERIN = "אילת ומיסוי מקרקרין"
    ASHKELON = "אשקלון"
    BEER_SHEVA = "באר שבע"
    LEMIFALIM_GDOLIM = "למפעלים גדולים"
    CHOLON = "חולון"
    NETANYA = "נתניה"
    PETAH_TIKVA = "פתח תקוה"
    REHOVOT = " רחובות"
